/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// DataDefaultChannelPermissionsAnyOf
    /// </summary>
    [DataContract(Name = "DataDefaultChannelPermissions_anyOf")]
    public partial class DataDefaultChannelPermissionsAnyOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataDefaultChannelPermissionsAnyOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DataDefaultChannelPermissionsAnyOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataDefaultChannelPermissionsAnyOf" /> class.
        /// </summary>
        /// <param name="permissions">Permission values to set for members in a &#x60;Group&#x60; (required).</param>
        public DataDefaultChannelPermissionsAnyOf(int permissions = default)
        {
            this.Permissions = permissions;
        }

        /// <summary>
        /// Permission values to set for members in a &#x60;Group&#x60;
        /// </summary>
        /// <value>Permission values to set for members in a &#x60;Group&#x60;</value>
        [DataMember(Name = "permissions", IsRequired = true, EmitDefaultValue = true)]
        public int Permissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataDefaultChannelPermissionsAnyOf {\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Permissions (int) minimum
            if (this.Permissions < (int)0)
            {
                yield return new ValidationResult("Invalid value for Permissions, must be a value greater than or equal to 0.", new [] { "Permissions" });
            }

            yield break;
        }
    }

}
