/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// DataResendVerification
    /// </summary>
    [DataContract(Name = "DataResendVerification")]
    public partial class DataResendVerification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataResendVerification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DataResendVerification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataResendVerification" /> class.
        /// </summary>
        /// <param name="email">Email associated with the account (required).</param>
        /// <param name="captcha">Captcha verification code.</param>
        public DataResendVerification(string email = default, string captcha = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for DataResendVerification and cannot be null");
            }
            this.Email = email;
            this.Captcha = captcha;
        }

        /// <summary>
        /// Email associated with the account
        /// </summary>
        /// <value>Email associated with the account</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Captcha verification code
        /// </summary>
        /// <value>Captcha verification code</value>
        [DataMember(Name = "captcha", EmitDefaultValue = true)]
        public string Captcha { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataResendVerification {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Captcha: ").Append(Captcha).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
