/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// DataChangeUsername
    /// </summary>
    [DataContract(Name = "DataChangeUsername")]
    public partial class DataChangeUsername : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataChangeUsername" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DataChangeUsername() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataChangeUsername" /> class.
        /// </summary>
        /// <param name="username">New username (required).</param>
        /// <param name="password">Current account password (required).</param>
        public DataChangeUsername(string username = default, string password = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for DataChangeUsername and cannot be null");
            }
            this.Username = username;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for DataChangeUsername and cannot be null");
            }
            this.Password = password;
        }

        /// <summary>
        /// New username
        /// </summary>
        /// <value>New username</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Current account password
        /// </summary>
        /// <value>Current account password</value>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataChangeUsername {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Username (string) maxLength
            if (this.Username != null && this.Username.Length > 32)
            {
                yield return new ValidationResult("Invalid value for Username, length must be less than 32.", new [] { "Username" });
            }

            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Username, length must be greater than 2.", new [] { "Username" });
            }

            if (this.Username != null) {
                // Username (string) pattern
                Regex regexUsername = new Regex(@"^(\p{L}|[\d_.-])+$", RegexOptions.CultureInvariant);
                if (!regexUsername.Match(this.Username).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Username, must match a pattern of " + regexUsername, new [] { "Username" });
                }
            }

            // Password (string) maxLength
            if (this.Password != null && this.Password.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Password, length must be less than 1024.", new [] { "Password" });
            }

            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 8)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 8.", new [] { "Password" });
            }

            yield break;
        }
    }

}
