/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Stoat.API.Model
{
    /// <summary>
    /// Embed
    /// </summary>
    [JsonConverter(typeof(EmbedJsonConverter))]
    [DataContract(Name = "Embed")]
    public partial class Embed : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Embed" /> class
        /// with the <see cref="EmbedOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbedOneOf.</param>
        public Embed(EmbedOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Embed" /> class
        /// with the <see cref="EmbedOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbedOneOf1.</param>
        public Embed(EmbedOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Embed" /> class
        /// with the <see cref="EmbedOneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbedOneOf2.</param>
        public Embed(EmbedOneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Embed" /> class
        /// with the <see cref="EmbedOneOf3" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbedOneOf3.</param>
        public Embed(EmbedOneOf3 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Embed" /> class
        /// with the <see cref="EmbedOneOf4" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbedOneOf4.</param>
        public Embed(EmbedOneOf4 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(EmbedOneOf) || value is EmbedOneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EmbedOneOf1) || value is EmbedOneOf1)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EmbedOneOf2) || value is EmbedOneOf2)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EmbedOneOf3) || value is EmbedOneOf3)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EmbedOneOf4) || value is EmbedOneOf4)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: EmbedOneOf, EmbedOneOf1, EmbedOneOf2, EmbedOneOf3, EmbedOneOf4");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `EmbedOneOf`. If the actual instance is not `EmbedOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbedOneOf</returns>
        public EmbedOneOf GetEmbedOneOf()
        {
            return (EmbedOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EmbedOneOf1`. If the actual instance is not `EmbedOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbedOneOf1</returns>
        public EmbedOneOf1 GetEmbedOneOf1()
        {
            return (EmbedOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EmbedOneOf2`. If the actual instance is not `EmbedOneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbedOneOf2</returns>
        public EmbedOneOf2 GetEmbedOneOf2()
        {
            return (EmbedOneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EmbedOneOf3`. If the actual instance is not `EmbedOneOf3`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbedOneOf3</returns>
        public EmbedOneOf3 GetEmbedOneOf3()
        {
            return (EmbedOneOf3)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EmbedOneOf4`. If the actual instance is not `EmbedOneOf4`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbedOneOf4</returns>
        public EmbedOneOf4 GetEmbedOneOf4()
        {
            return (EmbedOneOf4)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Embed {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, Embed.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Embed
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Embed</returns>
        public static Embed FromJson(string jsonString)
        {
            Embed newEmbed = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newEmbed;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbedOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf>(jsonString, Embed.SerializerSettings));
                }
                else
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf>(jsonString, Embed.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbedOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbedOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbedOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf1>(jsonString, Embed.SerializerSettings));
                }
                else
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf1>(jsonString, Embed.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbedOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbedOneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbedOneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf2>(jsonString, Embed.SerializerSettings));
                }
                else
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf2>(jsonString, Embed.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbedOneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbedOneOf2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbedOneOf3).GetProperty("AdditionalProperties") == null)
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf3>(jsonString, Embed.SerializerSettings));
                }
                else
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf3>(jsonString, Embed.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbedOneOf3");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbedOneOf3: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbedOneOf4).GetProperty("AdditionalProperties") == null)
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf4>(jsonString, Embed.SerializerSettings));
                }
                else
                {
                    newEmbed = new Embed(JsonConvert.DeserializeObject<EmbedOneOf4>(jsonString, Embed.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbedOneOf4");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbedOneOf4: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newEmbed;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Embed
    /// </summary>
    public class EmbedJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Embed).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return Embed.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Embed.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
