/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// Bot Response
    /// </summary>
    [DataContract(Name = "FetchBotResponse")]
    public partial class FetchBotResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchBotResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FetchBotResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchBotResponse" /> class.
        /// </summary>
        /// <param name="bot">Bot object (required).</param>
        /// <param name="user">User object (required).</param>
        public FetchBotResponse(Bot bot = default, User user = default)
        {
            // to ensure "bot" is required (not null)
            if (bot == null)
            {
                throw new ArgumentNullException("bot is a required property for FetchBotResponse and cannot be null");
            }
            this.Bot = bot;
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for FetchBotResponse and cannot be null");
            }
            this.User = user;
        }

        /// <summary>
        /// Bot object
        /// </summary>
        /// <value>Bot object</value>
        [DataMember(Name = "bot", IsRequired = true, EmitDefaultValue = true)]
        public Bot Bot { get; set; }

        /// <summary>
        /// User object
        /// </summary>
        /// <value>User object</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public User User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FetchBotResponse {\n");
            sb.Append("  Bot: ").Append(Bot).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
