/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// Type of remote Lightspeed.tv content
    /// </summary>
    /// <value>Type of remote Lightspeed.tv content</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LightspeedType
    {
        /// <summary>
        /// Enum Channel for value: Channel
        /// </summary>
        [EnumMember(Value = "Channel")]
        Channel = 1
    }

}
