/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// MFAResponseAnyOf1
    /// </summary>
    [DataContract(Name = "MFAResponse_anyOf_1")]
    public partial class MFAResponseAnyOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MFAResponseAnyOf1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MFAResponseAnyOf1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MFAResponseAnyOf1" /> class.
        /// </summary>
        /// <param name="recoveryCode">recoveryCode (required).</param>
        public MFAResponseAnyOf1(string recoveryCode = default)
        {
            // to ensure "recoveryCode" is required (not null)
            if (recoveryCode == null)
            {
                throw new ArgumentNullException("recoveryCode is a required property for MFAResponseAnyOf1 and cannot be null");
            }
            this.RecoveryCode = recoveryCode;
        }

        /// <summary>
        /// Gets or Sets RecoveryCode
        /// </summary>
        [DataMember(Name = "recovery_code", IsRequired = true, EmitDefaultValue = true)]
        public string RecoveryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MFAResponseAnyOf1 {\n");
            sb.Append("  RecoveryCode: ").Append(RecoveryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
