/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// Options for bulk deleting messages
    /// </summary>
    [DataContract(Name = "OptionsBulkDelete")]
    public partial class OptionsBulkDelete : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OptionsBulkDelete" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OptionsBulkDelete() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OptionsBulkDelete" /> class.
        /// </summary>
        /// <param name="ids">Message IDs (required).</param>
        public OptionsBulkDelete(List<string> ids = default)
        {
            // to ensure "ids" is required (not null)
            if (ids == null)
            {
                throw new ArgumentNullException("ids is a required property for OptionsBulkDelete and cannot be null");
            }
            this.Ids = ids;
        }

        /// <summary>
        /// Message IDs
        /// </summary>
        /// <value>Message IDs</value>
        [DataMember(Name = "ids", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Ids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OptionsBulkDelete {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
