/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// Report a message
    /// </summary>
    [DataContract(Name = "ReportedContent_oneOf")]
    public partial class ReportedContentOneOf : IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Message for value: Message
            /// </summary>
            [EnumMember(Value = "Message")]
            Message = 1
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Reason for reporting message
        /// </summary>
        /// <value>Reason for reporting message</value>
        [DataMember(Name = "report_reason", IsRequired = true, EmitDefaultValue = true)]
        public ContentReportReason ReportReason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportedContentOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReportedContentOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportedContentOneOf" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="id">ID of the message (required).</param>
        /// <param name="reportReason">Reason for reporting message (required).</param>
        public ReportedContentOneOf(TypeEnum type = default, string id = default, ContentReportReason reportReason = default)
        {
            this.Type = type;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ReportedContentOneOf and cannot be null");
            }
            this.Id = id;
            this.ReportReason = reportReason;
        }

        /// <summary>
        /// ID of the message
        /// </summary>
        /// <value>ID of the message</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReportedContentOneOf {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ReportReason: ").Append(ReportReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
