/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoat.API.Client.FileParameter;
using OpenAPIDateConverter = Stoat.API.Client.OpenAPIDateConverter;

namespace Stoat.API.Model
{
    /// <summary>
    /// User
    /// </summary>
    [DataContract(Name = "User")]
    public partial class User : IValidatableObject
    {

        /// <summary>
        /// Current session user&#39;s relationship with this user
        /// </summary>
        /// <value>Current session user&#39;s relationship with this user</value>
        [DataMember(Name = "relationship", IsRequired = true, EmitDefaultValue = true)]
        public RelationshipStatus Relationship { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected User() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        /// <param name="id">Unique Id (required).</param>
        /// <param name="username">Username (required).</param>
        /// <param name="discriminator">Discriminator (required).</param>
        /// <param name="displayName">Display name.</param>
        /// <param name="avatar">Avatar attachment.</param>
        /// <param name="relations">Relationships with other users.</param>
        /// <param name="badges">Bitfield of user badges  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserBadges.html.</param>
        /// <param name="status">User&#39;s current status.</param>
        /// <param name="flags">Enum of user flags  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserFlags.html.</param>
        /// <param name="privileged">Whether this user is privileged.</param>
        /// <param name="bot">Bot information.</param>
        /// <param name="relationship">Current session user&#39;s relationship with this user (required).</param>
        /// <param name="online">Whether this user is currently online (required).</param>
        public User(string id = default, string username = default, string discriminator = default, string displayName = default, File avatar = default, List<Relationship> relations = default, int badges = default, UserStatus status = default, int flags = default, bool privileged = default, BotInformation bot = default, RelationshipStatus relationship = default, bool online = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for User and cannot be null");
            }
            this.Id = id;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for User and cannot be null");
            }
            this.Username = username;
            // to ensure "discriminator" is required (not null)
            if (discriminator == null)
            {
                throw new ArgumentNullException("discriminator is a required property for User and cannot be null");
            }
            this.Discriminator = discriminator;
            this.Relationship = relationship;
            this.Online = online;
            this.DisplayName = displayName;
            this.Avatar = avatar;
            this.Relations = relations;
            this.Badges = badges;
            this.Status = status;
            this.Flags = flags;
            this.Privileged = privileged;
            this.Bot = bot;
        }

        /// <summary>
        /// Unique Id
        /// </summary>
        /// <value>Unique Id</value>
        [DataMember(Name = "_id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Username
        /// </summary>
        /// <value>Username</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Discriminator
        /// </summary>
        /// <value>Discriminator</value>
        [DataMember(Name = "discriminator", IsRequired = true, EmitDefaultValue = true)]
        public string Discriminator { get; set; }

        /// <summary>
        /// Display name
        /// </summary>
        /// <value>Display name</value>
        [DataMember(Name = "display_name", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Avatar attachment
        /// </summary>
        /// <value>Avatar attachment</value>
        [DataMember(Name = "avatar", EmitDefaultValue = true)]
        public File Avatar { get; set; }

        /// <summary>
        /// Relationships with other users
        /// </summary>
        /// <value>Relationships with other users</value>
        [DataMember(Name = "relations", EmitDefaultValue = false)]
        public List<Relationship> Relations { get; set; }

        /// <summary>
        /// Bitfield of user badges  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserBadges.html
        /// </summary>
        /// <value>Bitfield of user badges  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserBadges.html</value>
        [DataMember(Name = "badges", EmitDefaultValue = false)]
        public int Badges { get; set; }

        /// <summary>
        /// User&#39;s current status
        /// </summary>
        /// <value>User&#39;s current status</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public UserStatus Status { get; set; }

        /// <summary>
        /// Enum of user flags  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserFlags.html
        /// </summary>
        /// <value>Enum of user flags  https://docs.rs/revolt-models/latest/revolt_models/v0/enum.UserFlags.html</value>
        [DataMember(Name = "flags", EmitDefaultValue = false)]
        public int Flags { get; set; }

        /// <summary>
        /// Whether this user is privileged
        /// </summary>
        /// <value>Whether this user is privileged</value>
        [DataMember(Name = "privileged", EmitDefaultValue = true)]
        public bool Privileged { get; set; }

        /// <summary>
        /// Bot information
        /// </summary>
        /// <value>Bot information</value>
        [DataMember(Name = "bot", EmitDefaultValue = true)]
        public BotInformation Bot { get; set; }

        /// <summary>
        /// Whether this user is currently online
        /// </summary>
        /// <value>Whether this user is currently online</value>
        [DataMember(Name = "online", IsRequired = true, EmitDefaultValue = true)]
        public bool Online { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class User {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Discriminator: ").Append(Discriminator).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Relations: ").Append(Relations).Append("\n");
            sb.Append("  Badges: ").Append(Badges).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Flags: ").Append(Flags).Append("\n");
            sb.Append("  Privileged: ").Append(Privileged).Append("\n");
            sb.Append("  Bot: ").Append(Bot).Append("\n");
            sb.Append("  Relationship: ").Append(Relationship).Append("\n");
            sb.Append("  Online: ").Append(Online).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Badges (int) minimum
            if (this.Badges < (int)0)
            {
                yield return new ValidationResult("Invalid value for Badges, must be a value greater than or equal to 0.", new [] { "Badges" });
            }

            // Flags (int) minimum
            if (this.Flags < (int)0)
            {
                yield return new ValidationResult("Invalid value for Flags, must be a value greater than or equal to 0.", new [] { "Flags" });
            }

            yield break;
        }
    }

}
