/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Type of remote Bandcamp content
    /// </summary>
    /// <value>Type of remote Bandcamp content</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BandcampType
    {
        /// <summary>
        /// Enum Album for value: Album
        /// </summary>
        [EnumMember(Value = "Album")]
        Album = 1,

        /// <summary>
        /// Enum Track for value: Track
        /// </summary>
        [EnumMember(Value = "Track")]
        Track = 2
    }

}
