/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// CaptchaFeature
    /// </summary>
    [DataContract(Name = "CaptchaFeature")]
    public partial class CaptchaFeature : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaFeature" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CaptchaFeature() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaFeature" /> class.
        /// </summary>
        /// <param name="enabled">Whether captcha is enabled (required).</param>
        /// <param name="key">Client key used for solving captcha (required).</param>
        public CaptchaFeature(bool enabled = default, string key = default)
        {
            this.Enabled = enabled;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for CaptchaFeature and cannot be null");
            }
            this.Key = key;
        }

        /// <summary>
        /// Whether captcha is enabled
        /// </summary>
        /// <value>Whether captcha is enabled</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Client key used for solving captcha
        /// </summary>
        /// <value>Client key used for solving captcha</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptchaFeature {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
