/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Reason for reporting content (message or server)
    /// </summary>
    /// <value>Reason for reporting content (message or server)</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContentReportReason
    {
        /// <summary>
        /// Enum NoneSpecified for value: NoneSpecified
        /// </summary>
        [EnumMember(Value = "NoneSpecified")]
        NoneSpecified = 1,

        /// <summary>
        /// Enum Illegal for value: Illegal
        /// </summary>
        [EnumMember(Value = "Illegal")]
        Illegal = 2,

        /// <summary>
        /// Enum IllegalGoods for value: IllegalGoods
        /// </summary>
        [EnumMember(Value = "IllegalGoods")]
        IllegalGoods = 3,

        /// <summary>
        /// Enum IllegalExtortion for value: IllegalExtortion
        /// </summary>
        [EnumMember(Value = "IllegalExtortion")]
        IllegalExtortion = 4,

        /// <summary>
        /// Enum IllegalPornography for value: IllegalPornography
        /// </summary>
        [EnumMember(Value = "IllegalPornography")]
        IllegalPornography = 5,

        /// <summary>
        /// Enum IllegalHacking for value: IllegalHacking
        /// </summary>
        [EnumMember(Value = "IllegalHacking")]
        IllegalHacking = 6,

        /// <summary>
        /// Enum ExtremeViolence for value: ExtremeViolence
        /// </summary>
        [EnumMember(Value = "ExtremeViolence")]
        ExtremeViolence = 7,

        /// <summary>
        /// Enum PromotesHarm for value: PromotesHarm
        /// </summary>
        [EnumMember(Value = "PromotesHarm")]
        PromotesHarm = 8,

        /// <summary>
        /// Enum UnsolicitedSpam for value: UnsolicitedSpam
        /// </summary>
        [EnumMember(Value = "UnsolicitedSpam")]
        UnsolicitedSpam = 9,

        /// <summary>
        /// Enum Raid for value: Raid
        /// </summary>
        [EnumMember(Value = "Raid")]
        Raid = 10,

        /// <summary>
        /// Enum SpamAbuse for value: SpamAbuse
        /// </summary>
        [EnumMember(Value = "SpamAbuse")]
        SpamAbuse = 11,

        /// <summary>
        /// Enum ScamsFraud for value: ScamsFraud
        /// </summary>
        [EnumMember(Value = "ScamsFraud")]
        ScamsFraud = 12,

        /// <summary>
        /// Enum Malware for value: Malware
        /// </summary>
        [EnumMember(Value = "Malware")]
        Malware = 13,

        /// <summary>
        /// Enum Harassment for value: Harassment
        /// </summary>
        [EnumMember(Value = "Harassment")]
        Harassment = 14
    }

}
