/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// New webhook information
    /// </summary>
    [DataContract(Name = "DataEditChannel")]
    public partial class DataEditChannel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataEditChannel" /> class.
        /// </summary>
        /// <param name="name">Channel name.</param>
        /// <param name="description">Channel description.</param>
        /// <param name="owner">Group owner.</param>
        /// <param name="icon">Icon  Provide an Autumn attachment Id..</param>
        /// <param name="nsfw">Whether this channel is age-restricted.</param>
        /// <param name="archived">Whether this channel is archived.</param>
        /// <param name="voice">Voice Information for voice channels.</param>
        /// <param name="remove">Fields to remove from channel.</param>
        public DataEditChannel(string name = default, string description = default, string owner = default, string icon = default, bool? nsfw = default, bool? archived = default, VoiceInformation voice = default, List<FieldsChannel> remove = default)
        {
            this.Name = name;
            this.Description = description;
            this.Owner = owner;
            this.Icon = icon;
            this.Nsfw = nsfw;
            this.Archived = archived;
            this.Voice = voice;
            this.Remove = remove;
        }

        /// <summary>
        /// Channel name
        /// </summary>
        /// <value>Channel name</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Channel description
        /// </summary>
        /// <value>Channel description</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Group owner
        /// </summary>
        /// <value>Group owner</value>
        [DataMember(Name = "owner", EmitDefaultValue = true)]
        public string Owner { get; set; }

        /// <summary>
        /// Icon  Provide an Autumn attachment Id.
        /// </summary>
        /// <value>Icon  Provide an Autumn attachment Id.</value>
        [DataMember(Name = "icon", EmitDefaultValue = true)]
        public string Icon { get; set; }

        /// <summary>
        /// Whether this channel is age-restricted
        /// </summary>
        /// <value>Whether this channel is age-restricted</value>
        [DataMember(Name = "nsfw", EmitDefaultValue = true)]
        public bool? Nsfw { get; set; }

        /// <summary>
        /// Whether this channel is archived
        /// </summary>
        /// <value>Whether this channel is archived</value>
        [DataMember(Name = "archived", EmitDefaultValue = true)]
        public bool? Archived { get; set; }

        /// <summary>
        /// Voice Information for voice channels
        /// </summary>
        /// <value>Voice Information for voice channels</value>
        [DataMember(Name = "voice", EmitDefaultValue = true)]
        public VoiceInformation Voice { get; set; }

        /// <summary>
        /// Fields to remove from channel
        /// </summary>
        /// <value>Fields to remove from channel</value>
        [DataMember(Name = "remove", EmitDefaultValue = false)]
        public List<FieldsChannel> Remove { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataEditChannel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Nsfw: ").Append(Nsfw).Append("\n");
            sb.Append("  Archived: ").Append(Archived).Append("\n");
            sb.Append("  Voice: ").Append(Voice).Append("\n");
            sb.Append("  Remove: ").Append(Remove).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 32)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 32.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 1024.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 0.", new [] { "Description" });
            }

            // Icon (string) maxLength
            if (this.Icon != null && this.Icon.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Icon, length must be less than 128.", new [] { "Icon" });
            }

            // Icon (string) minLength
            if (this.Icon != null && this.Icon.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Icon, length must be greater than 1.", new [] { "Icon" });
            }

            yield break;
        }
    }

}
