/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// New user profile data
    /// </summary>
    [DataContract(Name = "DataUserProfile")]
    public partial class DataUserProfile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataUserProfile" /> class.
        /// </summary>
        /// <param name="content">Text to set as user profile description.</param>
        /// <param name="background">Attachment Id for background.</param>
        public DataUserProfile(string content = default, string background = default)
        {
            this.Content = content;
            this.Background = background;
        }

        /// <summary>
        /// Text to set as user profile description
        /// </summary>
        /// <value>Text to set as user profile description</value>
        [DataMember(Name = "content", EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// Attachment Id for background
        /// </summary>
        /// <value>Attachment Id for background</value>
        [DataMember(Name = "background", EmitDefaultValue = true)]
        public string Background { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataUserProfile {\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Background: ").Append(Background).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Content (string) maxLength
            if (this.Content != null && this.Content.Length > 2000)
            {
                yield return new ValidationResult("Invalid value for Content, length must be less than 2000.", new [] { "Content" });
            }

            // Content (string) minLength
            if (this.Content != null && this.Content.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Content, length must be greater than 0.", new [] { "Content" });
            }

            // Background (string) maxLength
            if (this.Background != null && this.Background.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Background, length must be less than 128.", new [] { "Background" });
            }

            // Background (string) minLength
            if (this.Background != null && this.Background.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Background, length must be greater than 1.", new [] { "Background" });
            }

            yield break;
        }
    }

}
