/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Create new server channel
    /// </summary>
    [DataContract(Name = "DataCreateServerChannel")]
    public partial class DataCreateServerChannel : IValidatableObject
    {

        /// <summary>
        /// Channel type
        /// </summary>
        /// <value>Channel type</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public LegacyServerChannelType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataCreateServerChannel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DataCreateServerChannel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataCreateServerChannel" /> class.
        /// </summary>
        /// <param name="type">Channel type.</param>
        /// <param name="name">Channel name (required).</param>
        /// <param name="description">Channel description.</param>
        /// <param name="nsfw">Whether this channel is age restricted.</param>
        /// <param name="voice">Voice Information for when this channel is also a voice channel.</param>
        public DataCreateServerChannel(LegacyServerChannelType? type = default, string name = default, string description = default, bool? nsfw = default, VoiceInformation voice = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DataCreateServerChannel and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            this.Description = description;
            this.Nsfw = nsfw;
            this.Voice = voice;
        }

        /// <summary>
        /// Channel name
        /// </summary>
        /// <value>Channel name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Channel description
        /// </summary>
        /// <value>Channel description</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Whether this channel is age restricted
        /// </summary>
        /// <value>Whether this channel is age restricted</value>
        [DataMember(Name = "nsfw", EmitDefaultValue = true)]
        public bool? Nsfw { get; set; }

        /// <summary>
        /// Voice Information for when this channel is also a voice channel
        /// </summary>
        /// <value>Voice Information for when this channel is also a voice channel</value>
        [DataMember(Name = "voice", EmitDefaultValue = true)]
        public VoiceInformation Voice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataCreateServerChannel {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Nsfw: ").Append(Nsfw).Append("\n");
            sb.Append("  Voice: ").Append(Voice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 32)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 32.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 1024.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 0.", new [] { "Description" });
            }

            yield break;
        }
    }

}
