/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Options for searching for messages
    /// </summary>
    [DataContract(Name = "DataMessageSearch")]
    public partial class DataMessageSearch : IValidatableObject
    {

        /// <summary>
        /// Message sort direction  By default, it will be sorted by latest.
        /// </summary>
        /// <value>Message sort direction  By default, it will be sorted by latest.</value>
        [DataMember(Name = "sort", EmitDefaultValue = false)]
        public MessageSort? Sort { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataMessageSearch" /> class.
        /// </summary>
        /// <param name="query">Full-text search query  See [MongoDB documentation](https://docs.mongodb.com/manual/text-search/#-text-operator) for more information..</param>
        /// <param name="pinned">Whether to only search for pinned messages, cannot be sent with &#x60;query&#x60;..</param>
        /// <param name="limit">Maximum number of messages to fetch.</param>
        /// <param name="before">Message id before which messages should be fetched.</param>
        /// <param name="after">Message id after which messages should be fetched.</param>
        /// <param name="sort">Message sort direction  By default, it will be sorted by latest..</param>
        /// <param name="includeUsers">Whether to include user (and member, if server channel) objects.</param>
        public DataMessageSearch(string query = default, bool? pinned = default, long? limit = default, string before = default, string after = default, MessageSort? sort = default, bool? includeUsers = default)
        {
            this.Query = query;
            this.Pinned = pinned;
            this.Limit = limit;
            this.Before = before;
            this.After = after;
            this.Sort = sort;
            this.IncludeUsers = includeUsers;
        }

        /// <summary>
        /// Full-text search query  See [MongoDB documentation](https://docs.mongodb.com/manual/text-search/#-text-operator) for more information.
        /// </summary>
        /// <value>Full-text search query  See [MongoDB documentation](https://docs.mongodb.com/manual/text-search/#-text-operator) for more information.</value>
        [DataMember(Name = "query", EmitDefaultValue = true)]
        public string Query { get; set; }

        /// <summary>
        /// Whether to only search for pinned messages, cannot be sent with &#x60;query&#x60;.
        /// </summary>
        /// <value>Whether to only search for pinned messages, cannot be sent with &#x60;query&#x60;.</value>
        [DataMember(Name = "pinned", EmitDefaultValue = true)]
        public bool? Pinned { get; set; }

        /// <summary>
        /// Maximum number of messages to fetch
        /// </summary>
        /// <value>Maximum number of messages to fetch</value>
        [DataMember(Name = "limit", EmitDefaultValue = true)]
        public long? Limit { get; set; }

        /// <summary>
        /// Message id before which messages should be fetched
        /// </summary>
        /// <value>Message id before which messages should be fetched</value>
        [DataMember(Name = "before", EmitDefaultValue = true)]
        public string Before { get; set; }

        /// <summary>
        /// Message id after which messages should be fetched
        /// </summary>
        /// <value>Message id after which messages should be fetched</value>
        [DataMember(Name = "after", EmitDefaultValue = true)]
        public string After { get; set; }

        /// <summary>
        /// Whether to include user (and member, if server channel) objects
        /// </summary>
        /// <value>Whether to include user (and member, if server channel) objects</value>
        [DataMember(Name = "include_users", EmitDefaultValue = true)]
        public bool? IncludeUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataMessageSearch {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Pinned: ").Append(Pinned).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Before: ").Append(Before).Append("\n");
            sb.Append("  After: ").Append(After).Append("\n");
            sb.Append("  Sort: ").Append(Sort).Append("\n");
            sb.Append("  IncludeUsers: ").Append(IncludeUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Query (string) maxLength
            if (this.Query != null && this.Query.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Query, length must be less than 64.", new [] { "Query" });
            }

            // Query (string) minLength
            if (this.Query != null && this.Query.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Query, length must be greater than 1.", new [] { "Query" });
            }

            // Limit (long?) maximum
            if (this.Limit > (long?)100)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value less than or equal to 100.", new [] { "Limit" });
            }

            // Limit (long?) minimum
            if (this.Limit < (long?)1)
            {
                yield return new ValidationResult("Invalid value for Limit, must be a value greater than or equal to 1.", new [] { "Limit" });
            }

            // Before (string) maxLength
            if (this.Before != null && this.Before.Length > 26)
            {
                yield return new ValidationResult("Invalid value for Before, length must be less than 26.", new [] { "Before" });
            }

            // Before (string) minLength
            if (this.Before != null && this.Before.Length < 26)
            {
                yield return new ValidationResult("Invalid value for Before, length must be greater than 26.", new [] { "Before" });
            }

            // After (string) maxLength
            if (this.After != null && this.After.Length > 26)
            {
                yield return new ValidationResult("Invalid value for After, length must be less than 26.", new [] { "After" });
            }

            // After (string) minLength
            if (this.After != null && this.After.Length < 26)
            {
                yield return new ValidationResult("Invalid value for After, length must be greater than 26.", new [] { "After" });
            }

            yield break;
        }
    }

}
