/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// New user information
    /// </summary>
    [DataContract(Name = "DataEditUser")]
    public partial class DataEditUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataEditUser" /> class.
        /// </summary>
        /// <param name="displayName">New display name.</param>
        /// <param name="avatar">Attachment Id for avatar.</param>
        /// <param name="status">New user status.</param>
        /// <param name="profile">New user profile data  This is applied as a partial..</param>
        /// <param name="badges">Bitfield of user badges.</param>
        /// <param name="flags">Enum of user flags.</param>
        /// <param name="remove">Fields to remove from user object.</param>
        public DataEditUser(string displayName = default, string avatar = default, UserStatus status = default, DataUserProfile profile = default, int? badges = default, int? flags = default, List<FieldsUser> remove = default)
        {
            this.DisplayName = displayName;
            this.Avatar = avatar;
            this.Status = status;
            this.Profile = profile;
            this.Badges = badges;
            this.Flags = flags;
            this.Remove = remove;
        }

        /// <summary>
        /// New display name
        /// </summary>
        /// <value>New display name</value>
        [DataMember(Name = "display_name", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Attachment Id for avatar
        /// </summary>
        /// <value>Attachment Id for avatar</value>
        [DataMember(Name = "avatar", EmitDefaultValue = true)]
        public string Avatar { get; set; }

        /// <summary>
        /// New user status
        /// </summary>
        /// <value>New user status</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public UserStatus Status { get; set; }

        /// <summary>
        /// New user profile data  This is applied as a partial.
        /// </summary>
        /// <value>New user profile data  This is applied as a partial.</value>
        [DataMember(Name = "profile", EmitDefaultValue = true)]
        public DataUserProfile Profile { get; set; }

        /// <summary>
        /// Bitfield of user badges
        /// </summary>
        /// <value>Bitfield of user badges</value>
        [DataMember(Name = "badges", EmitDefaultValue = true)]
        public int? Badges { get; set; }

        /// <summary>
        /// Enum of user flags
        /// </summary>
        /// <value>Enum of user flags</value>
        [DataMember(Name = "flags", EmitDefaultValue = true)]
        public int? Flags { get; set; }

        /// <summary>
        /// Fields to remove from user object
        /// </summary>
        /// <value>Fields to remove from user object</value>
        [DataMember(Name = "remove", EmitDefaultValue = false)]
        public List<FieldsUser> Remove { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataEditUser {\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  Badges: ").Append(Badges).Append("\n");
            sb.Append("  Flags: ").Append(Flags).Append("\n");
            sb.Append("  Remove: ").Append(Remove).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisplayName (string) maxLength
            if (this.DisplayName != null && this.DisplayName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be less than 32.", new [] { "DisplayName" });
            }

            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 2)
            {
                yield return new ValidationResult("Invalid value for DisplayName, length must be greater than 2.", new [] { "DisplayName" });
            }

            if (this.DisplayName != null) {
                // DisplayName (string) pattern
                Regex regexDisplayName = new Regex(@"^[^\u200B\n\r]+$", RegexOptions.CultureInvariant);
                if (!regexDisplayName.Match(this.DisplayName).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, must match a pattern of " + regexDisplayName, new [] { "DisplayName" });
                }
            }

            // Avatar (string) maxLength
            if (this.Avatar != null && this.Avatar.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Avatar, length must be less than 128.", new [] { "Avatar" });
            }

            // Avatar (string) minLength
            if (this.Avatar != null && this.Avatar.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Avatar, length must be greater than 1.", new [] { "Avatar" });
            }

            yield break;
        }
    }

}
