/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Join a voice channel
    /// </summary>
    [DataContract(Name = "DataJoinCall")]
    public partial class DataJoinCall : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataJoinCall" /> class.
        /// </summary>
        /// <param name="node">Name of the node to join.</param>
        /// <param name="forceDisconnect">Whether to force disconnect any other existing voice connections  Useful for disconnecting on another device and joining on a new..</param>
        /// <param name="recipients">Users which should be notified of the call starting  Only used when the user is the first one connected..</param>
        public DataJoinCall(string node = default, bool? forceDisconnect = default, List<string> recipients = default)
        {
            this.Node = node;
            this.ForceDisconnect = forceDisconnect;
            this.Recipients = recipients;
        }

        /// <summary>
        /// Name of the node to join
        /// </summary>
        /// <value>Name of the node to join</value>
        [DataMember(Name = "node", EmitDefaultValue = true)]
        public string Node { get; set; }

        /// <summary>
        /// Whether to force disconnect any other existing voice connections  Useful for disconnecting on another device and joining on a new.
        /// </summary>
        /// <value>Whether to force disconnect any other existing voice connections  Useful for disconnecting on another device and joining on a new.</value>
        [DataMember(Name = "force_disconnect", EmitDefaultValue = true)]
        public bool? ForceDisconnect { get; set; }

        /// <summary>
        /// Users which should be notified of the call starting  Only used when the user is the first one connected.
        /// </summary>
        /// <value>Users which should be notified of the call starting  Only used when the user is the first one connected.</value>
        [DataMember(Name = "recipients", EmitDefaultValue = true)]
        public List<string> Recipients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataJoinCall {\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  ForceDisconnect: ").Append(ForceDisconnect).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
