/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Image positioning and size
    /// </summary>
    /// <value>Image positioning and size</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImageSize
    {
        /// <summary>
        /// Enum Large for value: Large
        /// </summary>
        [EnumMember(Value = "Large")]
        Large = 1,

        /// <summary>
        /// Enum Preview for value: Preview
        /// </summary>
        [EnumMember(Value = "Preview")]
        Preview = 2
    }

}
