/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// MemberResponseAnyOf
    /// </summary>
    [DataContract(Name = "MemberResponse_anyOf")]
    public partial class MemberResponseAnyOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MemberResponseAnyOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MemberResponseAnyOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MemberResponseAnyOf" /> class.
        /// </summary>
        /// <param name="member">member (required).</param>
        /// <param name="roles">roles (required).</param>
        public MemberResponseAnyOf(Member member = default, Dictionary<string, Role> roles = default)
        {
            // to ensure "member" is required (not null)
            if (member == null)
            {
                throw new ArgumentNullException("member is a required property for MemberResponseAnyOf and cannot be null");
            }
            this.Member = member;
            // to ensure "roles" is required (not null)
            if (roles == null)
            {
                throw new ArgumentNullException("roles is a required property for MemberResponseAnyOf and cannot be null");
            }
            this.Roles = roles;
        }

        /// <summary>
        /// Gets or Sets Member
        /// </summary>
        [DataMember(Name = "member", IsRequired = true, EmitDefaultValue = true)]
        public Member Member { get; set; }

        /// <summary>
        /// Gets or Sets Roles
        /// </summary>
        [DataMember(Name = "roles", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Role> Roles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemberResponseAnyOf {\n");
            sb.Append("  Member: ").Append(Member).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
