/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// MFA response
    /// </summary>
    [JsonConverter(typeof(MFAResponseJsonConverter))]
    [DataContract(Name = "MFAResponse")]
    public partial class MFAResponse : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MFAResponse" /> class
        /// with the <see cref="MFAResponseAnyOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MFAResponseAnyOf.</param>
        public MFAResponse(MFAResponseAnyOf actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MFAResponse" /> class
        /// with the <see cref="MFAResponseAnyOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MFAResponseAnyOf1.</param>
        public MFAResponse(MFAResponseAnyOf1 actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MFAResponse" /> class
        /// with the <see cref="MFAResponseAnyOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MFAResponseAnyOf2.</param>
        public MFAResponse(MFAResponseAnyOf2 actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(MFAResponseAnyOf))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(MFAResponseAnyOf1))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(MFAResponseAnyOf2))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: MFAResponseAnyOf, MFAResponseAnyOf1, MFAResponseAnyOf2");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `MFAResponseAnyOf`. If the actual instance is not `MFAResponseAnyOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MFAResponseAnyOf</returns>
        public MFAResponseAnyOf GetMFAResponseAnyOf()
        {
            return (MFAResponseAnyOf)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MFAResponseAnyOf1`. If the actual instance is not `MFAResponseAnyOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MFAResponseAnyOf1</returns>
        public MFAResponseAnyOf1 GetMFAResponseAnyOf1()
        {
            return (MFAResponseAnyOf1)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MFAResponseAnyOf2`. If the actual instance is not `MFAResponseAnyOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MFAResponseAnyOf2</returns>
        public MFAResponseAnyOf2 GetMFAResponseAnyOf2()
        {
            return (MFAResponseAnyOf2)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MFAResponse {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, MFAResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of MFAResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of MFAResponse</returns>
        public static MFAResponse FromJson(string jsonString)
        {
            MFAResponse newMFAResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newMFAResponse;
            }

            try
            {
                newMFAResponse = new MFAResponse(JsonConvert.DeserializeObject<MFAResponseAnyOf>(jsonString, MFAResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMFAResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MFAResponseAnyOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newMFAResponse = new MFAResponse(JsonConvert.DeserializeObject<MFAResponseAnyOf1>(jsonString, MFAResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMFAResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MFAResponseAnyOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newMFAResponse = new MFAResponse(JsonConvert.DeserializeObject<MFAResponseAnyOf2>(jsonString, MFAResponse.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newMFAResponse;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MFAResponseAnyOf2: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for MFAResponse
    /// </summary>
    public class MFAResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(MFAResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return MFAResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return MFAResponse.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
