/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Representation of a single permission override as it appears on models and in the database
    /// </summary>
    [DataContract(Name = "OverrideField")]
    public partial class OverrideField : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OverrideField" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OverrideField() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OverrideField" /> class.
        /// </summary>
        /// <param name="a">Allow bit flags (required).</param>
        /// <param name="d">Disallow bit flags (required).</param>
        public OverrideField(long a = default, long d = default)
        {
            this.A = a;
            this.D = d;
        }

        /// <summary>
        /// Allow bit flags
        /// </summary>
        /// <value>Allow bit flags</value>
        [DataMember(Name = "a", IsRequired = true, EmitDefaultValue = true)]
        public long A { get; set; }

        /// <summary>
        /// Disallow bit flags
        /// </summary>
        /// <value>Disallow bit flags</value>
        [DataMember(Name = "d", IsRequired = true, EmitDefaultValue = true)]
        public long D { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OverrideField {\n");
            sb.Append("  A: ").Append(A).Append("\n");
            sb.Append("  D: ").Append(D).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
