/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Representation of a single permission override
    /// </summary>
    [DataContract(Name = "Override")]
    public partial class Override : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Override" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Override() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Override" /> class.
        /// </summary>
        /// <param name="allow">Allow bit flags (required).</param>
        /// <param name="deny">Disallow bit flags (required).</param>
        public Override(int allow = default, int deny = default)
        {
            this.Allow = allow;
            this.Deny = deny;
        }

        /// <summary>
        /// Allow bit flags
        /// </summary>
        /// <value>Allow bit flags</value>
        [DataMember(Name = "allow", IsRequired = true, EmitDefaultValue = true)]
        public int Allow { get; set; }

        /// <summary>
        /// Disallow bit flags
        /// </summary>
        /// <value>Disallow bit flags</value>
        [DataMember(Name = "deny", IsRequired = true, EmitDefaultValue = true)]
        public int Deny { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Override {\n");
            sb.Append("  Allow: ").Append(Allow).Append("\n");
            sb.Append("  Deny: ").Append(Deny).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Allow (int) minimum
            if (this.Allow < (int)0)
            {
                yield return new ValidationResult("Invalid value for Allow, must be a value greater than or equal to 0.", new [] { "Allow" });
            }

            // Deny (int) minimum
            if (this.Deny < (int)0)
            {
                yield return new ValidationResult("Invalid value for Deny, must be a value greater than or equal to 0.", new [] { "Deny" });
            }

            yield break;
        }
    }

}
