/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// The content being reported
    /// </summary>
    [JsonConverter(typeof(ReportedContentJsonConverter))]
    [DataContract(Name = "ReportedContent")]
    public partial class ReportedContent : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportedContent" /> class
        /// with the <see cref="ReportedContentOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ReportedContentOneOf.</param>
        public ReportedContent(ReportedContentOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportedContent" /> class
        /// with the <see cref="ReportedContentOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ReportedContentOneOf1.</param>
        public ReportedContent(ReportedContentOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportedContent" /> class
        /// with the <see cref="ReportedContentOneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ReportedContentOneOf2.</param>
        public ReportedContent(ReportedContentOneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ReportedContentOneOf) || value is ReportedContentOneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ReportedContentOneOf1) || value is ReportedContentOneOf1)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ReportedContentOneOf2) || value is ReportedContentOneOf2)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ReportedContentOneOf, ReportedContentOneOf1, ReportedContentOneOf2");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ReportedContentOneOf`. If the actual instance is not `ReportedContentOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ReportedContentOneOf</returns>
        public ReportedContentOneOf GetReportedContentOneOf()
        {
            return (ReportedContentOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ReportedContentOneOf1`. If the actual instance is not `ReportedContentOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ReportedContentOneOf1</returns>
        public ReportedContentOneOf1 GetReportedContentOneOf1()
        {
            return (ReportedContentOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ReportedContentOneOf2`. If the actual instance is not `ReportedContentOneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ReportedContentOneOf2</returns>
        public ReportedContentOneOf2 GetReportedContentOneOf2()
        {
            return (ReportedContentOneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportedContent {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ReportedContent.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ReportedContent
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ReportedContent</returns>
        public static ReportedContent FromJson(string jsonString)
        {
            ReportedContent newReportedContent = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newReportedContent;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ReportedContentOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf>(jsonString, ReportedContent.SerializerSettings));
                }
                else
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf>(jsonString, ReportedContent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ReportedContentOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ReportedContentOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ReportedContentOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf1>(jsonString, ReportedContent.SerializerSettings));
                }
                else
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf1>(jsonString, ReportedContent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ReportedContentOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ReportedContentOneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ReportedContentOneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf2>(jsonString, ReportedContent.SerializerSettings));
                }
                else
                {
                    newReportedContent = new ReportedContent(JsonConvert.DeserializeObject<ReportedContentOneOf2>(jsonString, ReportedContent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ReportedContentOneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ReportedContentOneOf2: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newReportedContent;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ReportedContent
    /// </summary>
    public class ReportedContentJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ReportedContent).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ReportedContent.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ReportedContent.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
