/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// RevoltFeatures
    /// </summary>
    [DataContract(Name = "RevoltFeatures")]
    public partial class RevoltFeatures : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RevoltFeatures" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RevoltFeatures() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RevoltFeatures" /> class.
        /// </summary>
        /// <param name="captcha">hCaptcha configuration (required).</param>
        /// <param name="email">Whether email verification is enabled (required).</param>
        /// <param name="inviteOnly">Whether this server is invite only (required).</param>
        /// <param name="autumn">File server service configuration (required).</param>
        /// <param name="january">Proxy service configuration (required).</param>
        /// <param name="livekit">Voice server configuration (required).</param>
        public RevoltFeatures(CaptchaFeature captcha = default, bool email = default, bool inviteOnly = default, Feature autumn = default, Feature january = default, VoiceFeature livekit = default)
        {
            // to ensure "captcha" is required (not null)
            if (captcha == null)
            {
                throw new ArgumentNullException("captcha is a required property for RevoltFeatures and cannot be null");
            }
            this.Captcha = captcha;
            this.Email = email;
            this.InviteOnly = inviteOnly;
            // to ensure "autumn" is required (not null)
            if (autumn == null)
            {
                throw new ArgumentNullException("autumn is a required property for RevoltFeatures and cannot be null");
            }
            this.Autumn = autumn;
            // to ensure "january" is required (not null)
            if (january == null)
            {
                throw new ArgumentNullException("january is a required property for RevoltFeatures and cannot be null");
            }
            this.January = january;
            // to ensure "livekit" is required (not null)
            if (livekit == null)
            {
                throw new ArgumentNullException("livekit is a required property for RevoltFeatures and cannot be null");
            }
            this.Livekit = livekit;
        }

        /// <summary>
        /// hCaptcha configuration
        /// </summary>
        /// <value>hCaptcha configuration</value>
        [DataMember(Name = "captcha", IsRequired = true, EmitDefaultValue = true)]
        public CaptchaFeature Captcha { get; set; }

        /// <summary>
        /// Whether email verification is enabled
        /// </summary>
        /// <value>Whether email verification is enabled</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public bool Email { get; set; }

        /// <summary>
        /// Whether this server is invite only
        /// </summary>
        /// <value>Whether this server is invite only</value>
        [DataMember(Name = "invite_only", IsRequired = true, EmitDefaultValue = true)]
        public bool InviteOnly { get; set; }

        /// <summary>
        /// File server service configuration
        /// </summary>
        /// <value>File server service configuration</value>
        [DataMember(Name = "autumn", IsRequired = true, EmitDefaultValue = true)]
        public Feature Autumn { get; set; }

        /// <summary>
        /// Proxy service configuration
        /// </summary>
        /// <value>Proxy service configuration</value>
        [DataMember(Name = "january", IsRequired = true, EmitDefaultValue = true)]
        public Feature January { get; set; }

        /// <summary>
        /// Voice server configuration
        /// </summary>
        /// <value>Voice server configuration</value>
        [DataMember(Name = "livekit", IsRequired = true, EmitDefaultValue = true)]
        public VoiceFeature Livekit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RevoltFeatures {\n");
            sb.Append("  Captcha: ").Append(Captcha).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  InviteOnly: ").Append(InviteOnly).Append("\n");
            sb.Append("  Autumn: ").Append(Autumn).Append("\n");
            sb.Append("  January: ").Append(January).Append("\n");
            sb.Append("  Livekit: ").Append(Livekit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
