/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Information about special remote content
    /// </summary>
    [JsonConverter(typeof(SpecialJsonConverter))]
    [DataContract(Name = "Special")]
    public partial class Special : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf.</param>
        public Special(SpecialOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf1.</param>
        public Special(SpecialOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf2.</param>
        public Special(SpecialOneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf3" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf3.</param>
        public Special(SpecialOneOf3 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf4" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf4.</param>
        public Special(SpecialOneOf4 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf5" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf5.</param>
        public Special(SpecialOneOf5 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf6" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf6.</param>
        public Special(SpecialOneOf6 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf7" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf7.</param>
        public Special(SpecialOneOf7 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf8" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf8.</param>
        public Special(SpecialOneOf8 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Special" /> class
        /// with the <see cref="SpecialOneOf9" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpecialOneOf9.</param>
        public Special(SpecialOneOf9 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(SpecialOneOf) || value is SpecialOneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf1) || value is SpecialOneOf1)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf2) || value is SpecialOneOf2)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf3) || value is SpecialOneOf3)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf4) || value is SpecialOneOf4)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf5) || value is SpecialOneOf5)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf6) || value is SpecialOneOf6)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf7) || value is SpecialOneOf7)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf8) || value is SpecialOneOf8)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpecialOneOf9) || value is SpecialOneOf9)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: SpecialOneOf, SpecialOneOf1, SpecialOneOf2, SpecialOneOf3, SpecialOneOf4, SpecialOneOf5, SpecialOneOf6, SpecialOneOf7, SpecialOneOf8, SpecialOneOf9");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf`. If the actual instance is not `SpecialOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf</returns>
        public SpecialOneOf GetSpecialOneOf()
        {
            return (SpecialOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf1`. If the actual instance is not `SpecialOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf1</returns>
        public SpecialOneOf1 GetSpecialOneOf1()
        {
            return (SpecialOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf2`. If the actual instance is not `SpecialOneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf2</returns>
        public SpecialOneOf2 GetSpecialOneOf2()
        {
            return (SpecialOneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf3`. If the actual instance is not `SpecialOneOf3`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf3</returns>
        public SpecialOneOf3 GetSpecialOneOf3()
        {
            return (SpecialOneOf3)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf4`. If the actual instance is not `SpecialOneOf4`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf4</returns>
        public SpecialOneOf4 GetSpecialOneOf4()
        {
            return (SpecialOneOf4)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf5`. If the actual instance is not `SpecialOneOf5`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf5</returns>
        public SpecialOneOf5 GetSpecialOneOf5()
        {
            return (SpecialOneOf5)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf6`. If the actual instance is not `SpecialOneOf6`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf6</returns>
        public SpecialOneOf6 GetSpecialOneOf6()
        {
            return (SpecialOneOf6)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf7`. If the actual instance is not `SpecialOneOf7`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf7</returns>
        public SpecialOneOf7 GetSpecialOneOf7()
        {
            return (SpecialOneOf7)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf8`. If the actual instance is not `SpecialOneOf8`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf8</returns>
        public SpecialOneOf8 GetSpecialOneOf8()
        {
            return (SpecialOneOf8)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpecialOneOf9`. If the actual instance is not `SpecialOneOf9`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpecialOneOf9</returns>
        public SpecialOneOf9 GetSpecialOneOf9()
        {
            return (SpecialOneOf9)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Special {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, Special.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Special
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Special</returns>
        public static Special FromJson(string jsonString)
        {
            Special newSpecial = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSpecial;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf1>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf1>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf2>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf2>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf3).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf3>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf3>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf3");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf3: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf4).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf4>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf4>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf4");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf4: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf5).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf5>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf5>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf5");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf5: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf6).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf6>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf6>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf6");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf6: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf7).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf7>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf7>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf7");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf7: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf8).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf8>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf8>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf8");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf8: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SpecialOneOf9).GetProperty("AdditionalProperties") == null)
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf9>(jsonString, Special.SerializerSettings));
                }
                else
                {
                    newSpecial = new Special(JsonConvert.DeserializeObject<SpecialOneOf9>(jsonString, Special.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SpecialOneOf9");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpecialOneOf9: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSpecial;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Special
    /// </summary>
    public class SpecialJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Special).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return Special.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Special.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
