/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// System Event
    /// </summary>
    [JsonConverter(typeof(SystemMessageJsonConverter))]
    [DataContract(Name = "SystemMessage")]
    public partial class SystemMessage : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf.</param>
        public SystemMessage(SystemMessageOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf1.</param>
        public SystemMessage(SystemMessageOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf2.</param>
        public SystemMessage(SystemMessageOneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf3" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf3.</param>
        public SystemMessage(SystemMessageOneOf3 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf4" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf4.</param>
        public SystemMessage(SystemMessageOneOf4 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf5" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf5.</param>
        public SystemMessage(SystemMessageOneOf5 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf6" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf6.</param>
        public SystemMessage(SystemMessageOneOf6 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf7" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf7.</param>
        public SystemMessage(SystemMessageOneOf7 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf8" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf8.</param>
        public SystemMessage(SystemMessageOneOf8 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf9" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf9.</param>
        public SystemMessage(SystemMessageOneOf9 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf10" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf10.</param>
        public SystemMessage(SystemMessageOneOf10 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf11" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf11.</param>
        public SystemMessage(SystemMessageOneOf11 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf12" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf12.</param>
        public SystemMessage(SystemMessageOneOf12 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemMessage" /> class
        /// with the <see cref="SystemMessageOneOf13" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMessageOneOf13.</param>
        public SystemMessage(SystemMessageOneOf13 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(SystemMessageOneOf) || value is SystemMessageOneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf1) || value is SystemMessageOneOf1)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf10) || value is SystemMessageOneOf10)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf11) || value is SystemMessageOneOf11)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf12) || value is SystemMessageOneOf12)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf13) || value is SystemMessageOneOf13)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf2) || value is SystemMessageOneOf2)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf3) || value is SystemMessageOneOf3)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf4) || value is SystemMessageOneOf4)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf5) || value is SystemMessageOneOf5)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf6) || value is SystemMessageOneOf6)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf7) || value is SystemMessageOneOf7)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf8) || value is SystemMessageOneOf8)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMessageOneOf9) || value is SystemMessageOneOf9)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: SystemMessageOneOf, SystemMessageOneOf1, SystemMessageOneOf10, SystemMessageOneOf11, SystemMessageOneOf12, SystemMessageOneOf13, SystemMessageOneOf2, SystemMessageOneOf3, SystemMessageOneOf4, SystemMessageOneOf5, SystemMessageOneOf6, SystemMessageOneOf7, SystemMessageOneOf8, SystemMessageOneOf9");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf`. If the actual instance is not `SystemMessageOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf</returns>
        public SystemMessageOneOf GetSystemMessageOneOf()
        {
            return (SystemMessageOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf1`. If the actual instance is not `SystemMessageOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf1</returns>
        public SystemMessageOneOf1 GetSystemMessageOneOf1()
        {
            return (SystemMessageOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf2`. If the actual instance is not `SystemMessageOneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf2</returns>
        public SystemMessageOneOf2 GetSystemMessageOneOf2()
        {
            return (SystemMessageOneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf3`. If the actual instance is not `SystemMessageOneOf3`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf3</returns>
        public SystemMessageOneOf3 GetSystemMessageOneOf3()
        {
            return (SystemMessageOneOf3)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf4`. If the actual instance is not `SystemMessageOneOf4`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf4</returns>
        public SystemMessageOneOf4 GetSystemMessageOneOf4()
        {
            return (SystemMessageOneOf4)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf5`. If the actual instance is not `SystemMessageOneOf5`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf5</returns>
        public SystemMessageOneOf5 GetSystemMessageOneOf5()
        {
            return (SystemMessageOneOf5)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf6`. If the actual instance is not `SystemMessageOneOf6`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf6</returns>
        public SystemMessageOneOf6 GetSystemMessageOneOf6()
        {
            return (SystemMessageOneOf6)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf7`. If the actual instance is not `SystemMessageOneOf7`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf7</returns>
        public SystemMessageOneOf7 GetSystemMessageOneOf7()
        {
            return (SystemMessageOneOf7)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf8`. If the actual instance is not `SystemMessageOneOf8`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf8</returns>
        public SystemMessageOneOf8 GetSystemMessageOneOf8()
        {
            return (SystemMessageOneOf8)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf9`. If the actual instance is not `SystemMessageOneOf9`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf9</returns>
        public SystemMessageOneOf9 GetSystemMessageOneOf9()
        {
            return (SystemMessageOneOf9)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf10`. If the actual instance is not `SystemMessageOneOf10`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf10</returns>
        public SystemMessageOneOf10 GetSystemMessageOneOf10()
        {
            return (SystemMessageOneOf10)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf11`. If the actual instance is not `SystemMessageOneOf11`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf11</returns>
        public SystemMessageOneOf11 GetSystemMessageOneOf11()
        {
            return (SystemMessageOneOf11)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf12`. If the actual instance is not `SystemMessageOneOf12`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf12</returns>
        public SystemMessageOneOf12 GetSystemMessageOneOf12()
        {
            return (SystemMessageOneOf12)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMessageOneOf13`. If the actual instance is not `SystemMessageOneOf13`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMessageOneOf13</returns>
        public SystemMessageOneOf13 GetSystemMessageOneOf13()
        {
            return (SystemMessageOneOf13)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SystemMessage {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, SystemMessage.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of SystemMessage
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of SystemMessage</returns>
        public static SystemMessage FromJson(string jsonString)
        {
            SystemMessage newSystemMessage = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newSystemMessage;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf1>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf1>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf10).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf10>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf10>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf10");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf10: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf11).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf11>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf11>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf11");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf11: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf12).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf12>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf12>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf12");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf12: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf13).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf13>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf13>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf13");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf13: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf2>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf2>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf3).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf3>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf3>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf3");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf3: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf4).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf4>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf4>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf4");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf4: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf5).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf5>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf5>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf5");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf5: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf6).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf6>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf6>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf6");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf6: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf7).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf7>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf7>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf7");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf7: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf8).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf8>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf8>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf8");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf8: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SystemMessageOneOf9).GetProperty("AdditionalProperties") == null)
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf9>(jsonString, SystemMessage.SerializerSettings));
                }
                else
                {
                    newSystemMessage = new SystemMessage(JsonConvert.DeserializeObject<SystemMessageOneOf9>(jsonString, SystemMessage.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SystemMessageOneOf9");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMessageOneOf9: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newSystemMessage;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for SystemMessage
    /// </summary>
    public class SystemMessageJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(SystemMessage).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return SystemMessage.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return SystemMessage.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
