/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Stoarp.APIClient.Client.FileParameter;
using OpenAPIDateConverter = Stoarp.APIClient.Client.OpenAPIDateConverter;

namespace Stoarp.APIClient.Model
{
    /// <summary>
    /// Web Push subscription
    /// </summary>
    [DataContract(Name = "WebPushSubscription")]
    public partial class WebPushSubscription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushSubscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebPushSubscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushSubscription" /> class.
        /// </summary>
        /// <param name="endpoint">endpoint (required).</param>
        /// <param name="p256dh">p256dh (required).</param>
        /// <param name="auth">auth (required).</param>
        public WebPushSubscription(string endpoint = default, string p256dh = default, string auth = default)
        {
            // to ensure "endpoint" is required (not null)
            if (endpoint == null)
            {
                throw new ArgumentNullException("endpoint is a required property for WebPushSubscription and cannot be null");
            }
            this.Endpoint = endpoint;
            // to ensure "p256dh" is required (not null)
            if (p256dh == null)
            {
                throw new ArgumentNullException("p256dh is a required property for WebPushSubscription and cannot be null");
            }
            this.P256dh = p256dh;
            // to ensure "auth" is required (not null)
            if (auth == null)
            {
                throw new ArgumentNullException("auth is a required property for WebPushSubscription and cannot be null");
            }
            this.Auth = auth;
        }

        /// <summary>
        /// Gets or Sets Endpoint
        /// </summary>
        [DataMember(Name = "endpoint", IsRequired = true, EmitDefaultValue = true)]
        public string Endpoint { get; set; }

        /// <summary>
        /// Gets or Sets P256dh
        /// </summary>
        [DataMember(Name = "p256dh", IsRequired = true, EmitDefaultValue = true)]
        public string P256dh { get; set; }

        /// <summary>
        /// Gets or Sets Auth
        /// </summary>
        [DataMember(Name = "auth", IsRequired = true, EmitDefaultValue = true)]
        public string Auth { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebPushSubscription {\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  P256dh: ").Append(P256dh).Append("\n");
            sb.Append("  Auth: ").Append(Auth).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
