/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Stoarp.APIClient.Client;
using Stoarp.APIClient.Model;

namespace Stoarp.APIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmojisApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create New Emoji
        /// </summary>
        /// <remarks>
        /// Create an emoji by its Autumn upload id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <returns>Emoji</returns>
        Emoji EmojiCreateCreateEmoji(string id, DataCreateEmoji dataCreateEmoji);

        /// <summary>
        /// Create New Emoji
        /// </summary>
        /// <remarks>
        /// Create an emoji by its Autumn upload id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <returns>ApiResponse of Emoji</returns>
        ApiResponse<Emoji> EmojiCreateCreateEmojiWithHttpInfo(string id, DataCreateEmoji dataCreateEmoji);
        /// <summary>
        /// Delete Emoji
        /// </summary>
        /// <remarks>
        /// Delete an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns></returns>
        void EmojiDeleteDeleteEmoji(string emojiId);

        /// <summary>
        /// Delete Emoji
        /// </summary>
        /// <remarks>
        /// Delete an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> EmojiDeleteDeleteEmojiWithHttpInfo(string emojiId);
        /// <summary>
        /// Fetch Emoji
        /// </summary>
        /// <remarks>
        /// Fetch an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>Emoji</returns>
        Emoji EmojiFetchFetchEmoji(string emojiId);

        /// <summary>
        /// Fetch Emoji
        /// </summary>
        /// <remarks>
        /// Fetch an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>ApiResponse of Emoji</returns>
        ApiResponse<Emoji> EmojiFetchFetchEmojiWithHttpInfo(string emojiId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmojisApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create New Emoji
        /// </summary>
        /// <remarks>
        /// Create an emoji by its Autumn upload id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Emoji</returns>
        System.Threading.Tasks.Task<Emoji> EmojiCreateCreateEmojiAsync(string id, DataCreateEmoji dataCreateEmoji, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create New Emoji
        /// </summary>
        /// <remarks>
        /// Create an emoji by its Autumn upload id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Emoji)</returns>
        System.Threading.Tasks.Task<ApiResponse<Emoji>> EmojiCreateCreateEmojiWithHttpInfoAsync(string id, DataCreateEmoji dataCreateEmoji, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete Emoji
        /// </summary>
        /// <remarks>
        /// Delete an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task EmojiDeleteDeleteEmojiAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete Emoji
        /// </summary>
        /// <remarks>
        /// Delete an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> EmojiDeleteDeleteEmojiWithHttpInfoAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Fetch Emoji
        /// </summary>
        /// <remarks>
        /// Fetch an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Emoji</returns>
        System.Threading.Tasks.Task<Emoji> EmojiFetchFetchEmojiAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Fetch Emoji
        /// </summary>
        /// <remarks>
        /// Fetch an emoji by its id.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Emoji)</returns>
        System.Threading.Tasks.Task<ApiResponse<Emoji>> EmojiFetchFetchEmojiWithHttpInfoAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmojisApi : IEmojisApiSync, IEmojisApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EmojisApi : IDisposable, IEmojisApi
    {
        private Stoarp.APIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public EmojisApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public EmojisApi(string basePath)
        {
            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                new Stoarp.APIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public EmojisApi(Stoarp.APIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EmojisApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EmojisApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                new Stoarp.APIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EmojisApi(HttpClient client, Stoarp.APIClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmojisApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public EmojisApi(Stoarp.APIClient.Client.ISynchronousClient client, Stoarp.APIClient.Client.IAsynchronousClient asyncClient, Stoarp.APIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Stoarp.APIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Stoarp.APIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Stoarp.APIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Stoarp.APIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Stoarp.APIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create New Emoji Create an emoji by its Autumn upload id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <returns>Emoji</returns>
        public Emoji EmojiCreateCreateEmoji(string id, DataCreateEmoji dataCreateEmoji)
        {
            Stoarp.APIClient.Client.ApiResponse<Emoji> localVarResponse = EmojiCreateCreateEmojiWithHttpInfo(id, dataCreateEmoji);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create New Emoji Create an emoji by its Autumn upload id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <returns>ApiResponse of Emoji</returns>
        public Stoarp.APIClient.Client.ApiResponse<Emoji> EmojiCreateCreateEmojiWithHttpInfo(string id, DataCreateEmoji dataCreateEmoji)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'id' when calling EmojisApi->EmojiCreateCreateEmoji");

            // verify the required parameter 'dataCreateEmoji' is set
            if (dataCreateEmoji == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'dataCreateEmoji' when calling EmojisApi->EmojiCreateCreateEmoji");

            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = dataCreateEmoji;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Emoji>("/custom/emoji/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiCreateCreateEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create New Emoji Create an emoji by its Autumn upload id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Emoji</returns>
        public async System.Threading.Tasks.Task<Emoji> EmojiCreateCreateEmojiAsync(string id, DataCreateEmoji dataCreateEmoji, System.Threading.CancellationToken cancellationToken = default)
        {
            Stoarp.APIClient.Client.ApiResponse<Emoji> localVarResponse = await EmojiCreateCreateEmojiWithHttpInfoAsync(id, dataCreateEmoji, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create New Emoji Create an emoji by its Autumn upload id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="dataCreateEmoji"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Emoji)</returns>
        public async System.Threading.Tasks.Task<Stoarp.APIClient.Client.ApiResponse<Emoji>> EmojiCreateCreateEmojiWithHttpInfoAsync(string id, DataCreateEmoji dataCreateEmoji, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'id' when calling EmojisApi->EmojiCreateCreateEmoji");

            // verify the required parameter 'dataCreateEmoji' is set
            if (dataCreateEmoji == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'dataCreateEmoji' when calling EmojisApi->EmojiCreateCreateEmoji");


            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = dataCreateEmoji;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Emoji>("/custom/emoji/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiCreateCreateEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Emoji Delete an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns></returns>
        public void EmojiDeleteDeleteEmoji(string emojiId)
        {
            EmojiDeleteDeleteEmojiWithHttpInfo(emojiId);
        }

        /// <summary>
        /// Delete Emoji Delete an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Stoarp.APIClient.Client.ApiResponse<Object> EmojiDeleteDeleteEmojiWithHttpInfo(string emojiId)
        {
            // verify the required parameter 'emojiId' is set
            if (emojiId == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'emojiId' when calling EmojisApi->EmojiDeleteDeleteEmoji");

            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("emoji_id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(emojiId)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/custom/emoji/{emoji_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiDeleteDeleteEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Emoji Delete an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task EmojiDeleteDeleteEmojiAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default)
        {
            await EmojiDeleteDeleteEmojiWithHttpInfoAsync(emojiId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete Emoji Delete an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Stoarp.APIClient.Client.ApiResponse<Object>> EmojiDeleteDeleteEmojiWithHttpInfoAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'emojiId' is set
            if (emojiId == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'emojiId' when calling EmojisApi->EmojiDeleteDeleteEmoji");


            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("emoji_id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(emojiId)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/custom/emoji/{emoji_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiDeleteDeleteEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch Emoji Fetch an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>Emoji</returns>
        public Emoji EmojiFetchFetchEmoji(string emojiId)
        {
            Stoarp.APIClient.Client.ApiResponse<Emoji> localVarResponse = EmojiFetchFetchEmojiWithHttpInfo(emojiId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Emoji Fetch an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <returns>ApiResponse of Emoji</returns>
        public Stoarp.APIClient.Client.ApiResponse<Emoji> EmojiFetchFetchEmojiWithHttpInfo(string emojiId)
        {
            // verify the required parameter 'emojiId' is set
            if (emojiId == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'emojiId' when calling EmojisApi->EmojiFetchFetchEmoji");

            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("emoji_id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(emojiId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<Emoji>("/custom/emoji/{emoji_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiFetchFetchEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch Emoji Fetch an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Emoji</returns>
        public async System.Threading.Tasks.Task<Emoji> EmojiFetchFetchEmojiAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default)
        {
            Stoarp.APIClient.Client.ApiResponse<Emoji> localVarResponse = await EmojiFetchFetchEmojiWithHttpInfoAsync(emojiId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Emoji Fetch an emoji by its id.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="emojiId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Emoji)</returns>
        public async System.Threading.Tasks.Task<Stoarp.APIClient.Client.ApiResponse<Emoji>> EmojiFetchFetchEmojiWithHttpInfoAsync(string emojiId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'emojiId' is set
            if (emojiId == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'emojiId' when calling EmojisApi->EmojiFetchFetchEmoji");


            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("emoji_id", Stoarp.APIClient.Client.ClientUtils.ParameterToString(emojiId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Emoji>("/custom/emoji/{emoji_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EmojiFetchFetchEmoji", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
