/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Stoarp.APIClient.Client;
using Stoarp.APIClient.Model;

namespace Stoarp.APIClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebPushApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Push Subscribe
        /// </summary>
        /// <remarks>
        /// Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <returns></returns>
        void SubscribeSubscribe(WebPushSubscription webPushSubscription);

        /// <summary>
        /// Push Subscribe
        /// </summary>
        /// <remarks>
        /// Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SubscribeSubscribeWithHttpInfo(WebPushSubscription webPushSubscription);
        /// <summary>
        /// Unsubscribe
        /// </summary>
        /// <remarks>
        /// Remove the Web Push subscription associated with the current session.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void UnsubscribeUnsubscribe();

        /// <summary>
        /// Unsubscribe
        /// </summary>
        /// <remarks>
        /// Remove the Web Push subscription associated with the current session.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UnsubscribeUnsubscribeWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebPushApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Push Subscribe
        /// </summary>
        /// <remarks>
        /// Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SubscribeSubscribeAsync(WebPushSubscription webPushSubscription, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Push Subscribe
        /// </summary>
        /// <remarks>
        /// Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SubscribeSubscribeWithHttpInfoAsync(WebPushSubscription webPushSubscription, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Unsubscribe
        /// </summary>
        /// <remarks>
        /// Remove the Web Push subscription associated with the current session.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UnsubscribeUnsubscribeAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Unsubscribe
        /// </summary>
        /// <remarks>
        /// Remove the Web Push subscription associated with the current session.
        /// </remarks>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UnsubscribeUnsubscribeWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebPushApi : IWebPushApiSync, IWebPushApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebPushApi : IDisposable, IWebPushApi
    {
        private Stoarp.APIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public WebPushApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public WebPushApi(string basePath)
        {
            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                new Stoarp.APIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public WebPushApi(Stoarp.APIClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebPushApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebPushApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                new Stoarp.APIClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public WebPushApi(HttpClient client, Stoarp.APIClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoarp.APIClient.Client.Configuration.MergeConfigurations(
                Stoarp.APIClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoarp.APIClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebPushApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public WebPushApi(Stoarp.APIClient.Client.ISynchronousClient client, Stoarp.APIClient.Client.IAsynchronousClient asyncClient, Stoarp.APIClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Stoarp.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Stoarp.APIClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Stoarp.APIClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Stoarp.APIClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Stoarp.APIClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Stoarp.APIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Push Subscribe Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <returns></returns>
        public void SubscribeSubscribe(WebPushSubscription webPushSubscription)
        {
            SubscribeSubscribeWithHttpInfo(webPushSubscription);
        }

        /// <summary>
        /// Push Subscribe Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Stoarp.APIClient.Client.ApiResponse<Object> SubscribeSubscribeWithHttpInfo(WebPushSubscription webPushSubscription)
        {
            // verify the required parameter 'webPushSubscription' is set
            if (webPushSubscription == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'webPushSubscription' when calling WebPushApi->SubscribeSubscribe");

            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webPushSubscription;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/push/subscribe", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SubscribeSubscribe", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Push Subscribe Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SubscribeSubscribeAsync(WebPushSubscription webPushSubscription, System.Threading.CancellationToken cancellationToken = default)
        {
            await SubscribeSubscribeWithHttpInfoAsync(webPushSubscription, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Push Subscribe Create a new Web Push subscription.  If an existing subscription exists on this session, it will be removed.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webPushSubscription"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Stoarp.APIClient.Client.ApiResponse<Object>> SubscribeSubscribeWithHttpInfoAsync(WebPushSubscription webPushSubscription, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'webPushSubscription' is set
            if (webPushSubscription == null)
                throw new Stoarp.APIClient.Client.ApiException(400, "Missing required parameter 'webPushSubscription' when calling WebPushApi->SubscribeSubscribe");


            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webPushSubscription;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/push/subscribe", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SubscribeSubscribe", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Unsubscribe Remove the Web Push subscription associated with the current session.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void UnsubscribeUnsubscribe()
        {
            UnsubscribeUnsubscribeWithHttpInfo();
        }

        /// <summary>
        /// Unsubscribe Remove the Web Push subscription associated with the current session.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public Stoarp.APIClient.Client.ApiResponse<Object> UnsubscribeUnsubscribeWithHttpInfo()
        {
            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/push/unsubscribe", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnsubscribeUnsubscribe", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Unsubscribe Remove the Web Push subscription associated with the current session.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UnsubscribeUnsubscribeAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            await UnsubscribeUnsubscribeWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Unsubscribe Remove the Web Push subscription associated with the current session.
        /// </summary>
        /// <exception cref="Stoarp.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Stoarp.APIClient.Client.ApiResponse<Object>> UnsubscribeUnsubscribeWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Stoarp.APIClient.Client.RequestOptions localVarRequestOptions = new Stoarp.APIClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoarp.APIClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoarp.APIClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/push/unsubscribe", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UnsubscribeUnsubscribe", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
