/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: contact@revolt.chat
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Stoat.API.Client;
using Stoat.API.Model;

namespace Stoat.API.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add Member to Group
        /// </summary>
        /// <remarks>
        /// Adds another user to the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <returns></returns>
        void GroupAddMemberAddMember(string groupId, string memberId);

        /// <summary>
        /// Add Member to Group
        /// </summary>
        /// <remarks>
        /// Adds another user to the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GroupAddMemberAddMemberWithHttpInfo(string groupId, string memberId);
        /// <summary>
        /// Create Group
        /// </summary>
        /// <remarks>
        /// Create a new group channel.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <returns>Channel</returns>
        Channel GroupCreateCreateGroup(DataCreateGroup dataCreateGroup);

        /// <summary>
        /// Create Group
        /// </summary>
        /// <remarks>
        /// Create a new group channel.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <returns>ApiResponse of Channel</returns>
        ApiResponse<Channel> GroupCreateCreateGroupWithHttpInfo(DataCreateGroup dataCreateGroup);
        /// <summary>
        /// Remove Member from Group
        /// </summary>
        /// <remarks>
        /// Removes a user from the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <returns></returns>
        void GroupRemoveMemberRemoveMember(string target, string member);

        /// <summary>
        /// Remove Member from Group
        /// </summary>
        /// <remarks>
        /// Removes a user from the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GroupRemoveMemberRemoveMemberWithHttpInfo(string target, string member);
        /// <summary>
        /// Fetch Group Members
        /// </summary>
        /// <remarks>
        /// Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <returns>List&lt;User&gt;</returns>
        List<User> MembersFetchFetchMembers(string target);

        /// <summary>
        /// Fetch Group Members
        /// </summary>
        /// <remarks>
        /// Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        ApiResponse<List<User>> MembersFetchFetchMembersWithHttpInfo(string target);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Add Member to Group
        /// </summary>
        /// <remarks>
        /// Adds another user to the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GroupAddMemberAddMemberAsync(string groupId, string memberId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Add Member to Group
        /// </summary>
        /// <remarks>
        /// Adds another user to the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GroupAddMemberAddMemberWithHttpInfoAsync(string groupId, string memberId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create Group
        /// </summary>
        /// <remarks>
        /// Create a new group channel.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        System.Threading.Tasks.Task<Channel> GroupCreateCreateGroupAsync(DataCreateGroup dataCreateGroup, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Group
        /// </summary>
        /// <remarks>
        /// Create a new group channel.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Channel>> GroupCreateCreateGroupWithHttpInfoAsync(DataCreateGroup dataCreateGroup, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Remove Member from Group
        /// </summary>
        /// <remarks>
        /// Removes a user from the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GroupRemoveMemberRemoveMemberAsync(string target, string member, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Remove Member from Group
        /// </summary>
        /// <remarks>
        /// Removes a user from the group.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GroupRemoveMemberRemoveMemberWithHttpInfoAsync(string target, string member, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Fetch Group Members
        /// </summary>
        /// <remarks>
        /// Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;User&gt;</returns>
        System.Threading.Tasks.Task<List<User>> MembersFetchFetchMembersAsync(string target, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Fetch Group Members
        /// </summary>
        /// <remarks>
        /// Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </remarks>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<User>>> MembersFetchFetchMembersWithHttpInfoAsync(string target, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupsApi : IGroupsApiSync, IGroupsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GroupsApi : IDisposable, IGroupsApi
    {
        private Stoat.API.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public GroupsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public GroupsApi(string basePath)
        {
            this.Configuration = Stoat.API.Client.Configuration.MergeConfigurations(
                Stoat.API.Client.GlobalConfiguration.Instance,
                new Stoat.API.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoat.API.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoat.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public GroupsApi(Stoat.API.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Stoat.API.Client.Configuration.MergeConfigurations(
                Stoat.API.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoat.API.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoat.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GroupsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GroupsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoat.API.Client.Configuration.MergeConfigurations(
                Stoat.API.Client.GlobalConfiguration.Instance,
                new Stoat.API.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Stoat.API.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Stoat.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public GroupsApi(HttpClient client, Stoat.API.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Stoat.API.Client.Configuration.MergeConfigurations(
                Stoat.API.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Stoat.API.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Stoat.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public GroupsApi(Stoat.API.Client.ISynchronousClient client, Stoat.API.Client.IAsynchronousClient asyncClient, Stoat.API.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Stoat.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Stoat.API.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Stoat.API.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Stoat.API.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Stoat.API.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Stoat.API.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Add Member to Group Adds another user to the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <returns></returns>
        public void GroupAddMemberAddMember(string groupId, string memberId)
        {
            GroupAddMemberAddMemberWithHttpInfo(groupId, memberId);
        }

        /// <summary>
        /// Add Member to Group Adds another user to the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Stoat.API.Client.ApiResponse<Object> GroupAddMemberAddMemberWithHttpInfo(string groupId, string memberId)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'groupId' when calling GroupsApi->GroupAddMemberAddMember");

            // verify the required parameter 'memberId' is set
            if (memberId == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'memberId' when calling GroupsApi->GroupAddMemberAddMember");

            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("group_id", Stoat.API.Client.ClientUtils.ParameterToString(groupId)); // path parameter
            localVarRequestOptions.PathParameters.Add("member_id", Stoat.API.Client.ClientUtils.ParameterToString(memberId)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/channels/{group_id}/recipients/{member_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupAddMemberAddMember", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Add Member to Group Adds another user to the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GroupAddMemberAddMemberAsync(string groupId, string memberId, System.Threading.CancellationToken cancellationToken = default)
        {
            await GroupAddMemberAddMemberWithHttpInfoAsync(groupId, memberId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Add Member to Group Adds another user to the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="memberId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Stoat.API.Client.ApiResponse<Object>> GroupAddMemberAddMemberWithHttpInfoAsync(string groupId, string memberId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'groupId' when calling GroupsApi->GroupAddMemberAddMember");

            // verify the required parameter 'memberId' is set
            if (memberId == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'memberId' when calling GroupsApi->GroupAddMemberAddMember");


            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("group_id", Stoat.API.Client.ClientUtils.ParameterToString(groupId)); // path parameter
            localVarRequestOptions.PathParameters.Add("member_id", Stoat.API.Client.ClientUtils.ParameterToString(memberId)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/channels/{group_id}/recipients/{member_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupAddMemberAddMember", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Group Create a new group channel.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <returns>Channel</returns>
        public Channel GroupCreateCreateGroup(DataCreateGroup dataCreateGroup)
        {
            Stoat.API.Client.ApiResponse<Channel> localVarResponse = GroupCreateCreateGroupWithHttpInfo(dataCreateGroup);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Group Create a new group channel.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <returns>ApiResponse of Channel</returns>
        public Stoat.API.Client.ApiResponse<Channel> GroupCreateCreateGroupWithHttpInfo(DataCreateGroup dataCreateGroup)
        {
            // verify the required parameter 'dataCreateGroup' is set
            if (dataCreateGroup == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'dataCreateGroup' when calling GroupsApi->GroupCreateCreateGroup");

            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dataCreateGroup;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Channel>("/channels/create", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupCreateCreateGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Group Create a new group channel.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Channel</returns>
        public async System.Threading.Tasks.Task<Channel> GroupCreateCreateGroupAsync(DataCreateGroup dataCreateGroup, System.Threading.CancellationToken cancellationToken = default)
        {
            Stoat.API.Client.ApiResponse<Channel> localVarResponse = await GroupCreateCreateGroupWithHttpInfoAsync(dataCreateGroup, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Group Create a new group channel.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataCreateGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Channel)</returns>
        public async System.Threading.Tasks.Task<Stoat.API.Client.ApiResponse<Channel>> GroupCreateCreateGroupWithHttpInfoAsync(DataCreateGroup dataCreateGroup, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dataCreateGroup' is set
            if (dataCreateGroup == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'dataCreateGroup' when calling GroupsApi->GroupCreateCreateGroup");


            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dataCreateGroup;

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Channel>("/channels/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupCreateCreateGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove Member from Group Removes a user from the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <returns></returns>
        public void GroupRemoveMemberRemoveMember(string target, string member)
        {
            GroupRemoveMemberRemoveMemberWithHttpInfo(target, member);
        }

        /// <summary>
        /// Remove Member from Group Removes a user from the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Stoat.API.Client.ApiResponse<Object> GroupRemoveMemberRemoveMemberWithHttpInfo(string target, string member)
        {
            // verify the required parameter 'target' is set
            if (target == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'target' when calling GroupsApi->GroupRemoveMemberRemoveMember");

            // verify the required parameter 'member' is set
            if (member == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'member' when calling GroupsApi->GroupRemoveMemberRemoveMember");

            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("target", Stoat.API.Client.ClientUtils.ParameterToString(target)); // path parameter
            localVarRequestOptions.PathParameters.Add("member", Stoat.API.Client.ClientUtils.ParameterToString(member)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/channels/{target}/recipients/{member}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupRemoveMemberRemoveMember", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove Member from Group Removes a user from the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GroupRemoveMemberRemoveMemberAsync(string target, string member, System.Threading.CancellationToken cancellationToken = default)
        {
            await GroupRemoveMemberRemoveMemberWithHttpInfoAsync(target, member, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Remove Member from Group Removes a user from the group.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="member"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Stoat.API.Client.ApiResponse<Object>> GroupRemoveMemberRemoveMemberWithHttpInfoAsync(string target, string member, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'target' is set
            if (target == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'target' when calling GroupsApi->GroupRemoveMemberRemoveMember");

            // verify the required parameter 'member' is set
            if (member == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'member' when calling GroupsApi->GroupRemoveMemberRemoveMember");


            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("target", Stoat.API.Client.ClientUtils.ParameterToString(target)); // path parameter
            localVarRequestOptions.PathParameters.Add("member", Stoat.API.Client.ClientUtils.ParameterToString(member)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/channels/{target}/recipients/{member}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GroupRemoveMemberRemoveMember", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch Group Members Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <returns>List&lt;User&gt;</returns>
        public List<User> MembersFetchFetchMembers(string target)
        {
            Stoat.API.Client.ApiResponse<List<User>> localVarResponse = MembersFetchFetchMembersWithHttpInfo(target);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Group Members Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <returns>ApiResponse of List&lt;User&gt;</returns>
        public Stoat.API.Client.ApiResponse<List<User>> MembersFetchFetchMembersWithHttpInfo(string target)
        {
            // verify the required parameter 'target' is set
            if (target == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'target' when calling GroupsApi->MembersFetchFetchMembers");

            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("target", Stoat.API.Client.ClientUtils.ParameterToString(target)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<User>>("/channels/{target}/members", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MembersFetchFetchMembers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch Group Members Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;User&gt;</returns>
        public async System.Threading.Tasks.Task<List<User>> MembersFetchFetchMembersAsync(string target, System.Threading.CancellationToken cancellationToken = default)
        {
            Stoat.API.Client.ApiResponse<List<User>> localVarResponse = await MembersFetchFetchMembersWithHttpInfoAsync(target, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch Group Members Retrieves all users who are part of this group.  This may not return full user information if users are not friends but have mutual connections.
        /// </summary>
        /// <exception cref="Stoat.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="target"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;User&gt;)</returns>
        public async System.Threading.Tasks.Task<Stoat.API.Client.ApiResponse<List<User>>> MembersFetchFetchMembersWithHttpInfoAsync(string target, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'target' is set
            if (target == null)
                throw new Stoat.API.Client.ApiException(400, "Missing required parameter 'target' when calling GroupsApi->MembersFetchFetchMembers");


            Stoat.API.Client.RequestOptions localVarRequestOptions = new Stoat.API.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Stoat.API.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Stoat.API.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("target", Stoat.API.Client.ClientUtils.ParameterToString(target)); // path parameter

            // authentication (Session_Token) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-session-token")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-session-token", this.Configuration.GetApiKeyWithPrefix("x-session-token"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<User>>("/channels/{target}/members", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MembersFetchFetchMembers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
